### ISSUE TITLE
Getting return typeof element?.type === 'string'; when migrating to testing-library v.11 from v.9

### ISSUE THREAD

**Issue by alex-mironov** [callstack/react-native-testing-library#1079]
## Describe the bug
For some reason after upgrading to the newer version of react-native and testing-library it fails to parse test files:

```
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.



    Details:

    ..../node_modules/@testing-library/react-native/build/fireEvent.js:13
      return typeof element?.type === 'string';
                            ^

    SyntaxError: Unexpected token '.'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (node_modules/@testing-library/react-native/src/pure.ts:3:1)
```

## Versions
```
    "react-native": "0.69.4",
    "@testing-library/jest-native": "4.0.11",
    "@testing-library/react-native": "11.0.0",
    "jest": "28.1.3",
...
    "@babel/core": "^7.18.13",
    "babel-jest": "28.1.3",
    "@babel/preset-env": "^7.18.10",
    "babel-plugin-module-resolver": "^4.1.0",
    "@babel/runtime": "^7.18.9",
```

What's weird it was working on version 9.

## jest.config.js
```
module.exports = {
  preset: 'react-native',
  testMatch: [
    '**/?(*.)(spec|test).js?(x)'
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
  ],
  moduleNameMapper: {
    '^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': 'identity-obj-proxy',
    'styled-components': '<rootDir>/node_modules/styled-components/native/dist/styled-components.native.cjs.js',
    '\\.svg': '<rootDir>/__mocks__/svgMock.js',
    'i18n-js': '<rootDir>/__mocks__/reacti18nextMock.js'
  },
  transform: {
    // '^.+\\.(js)$': '<rootDir>/node_modules/react-native/jest/preprocessor.js'
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|@react-native(-community)?|@react-navigation/.*|native-base|@react-native-firebase/.*|react-native-firebase|rn-color-matrices|concat-color-matrices)'
  ],
  setupFilesAfterEnv: [
    '@testing-library/jest-native/extend-expect',
    '<rootDir>/jest.setup.js',
    './node_modules/@react-native-community/datetimepicker/jest/setup.js'
  ]
}

```

**Comment by mdjastrzebski** [comment]
@alex-mironov Did you solve your issue? If so please describe it here, as it might help other users who encounter similar case.

**Comment by alex-mironov** [comment]
`pod install --repo-update` helped, I believe there was some weird issue with old version being stuck.

**Comment by mdjastrzebski** [comment]
@alex-mironov `pod install` is responsible for native iOS packages, while Jest is JS package taken from NPM repo, so this two should not be related. Seems like you might have made some other changes, on JS-side that fixed the issue.
