### ISSUE TITLE
Tests fail when using a ListHeaderComponent on a FlatList or VirtualizedList

### ISSUE THREAD

**Issue by wmcbain** [callstack/react-native-testing-library#117]
Hey there,

I'm using a FlatList with a ListHeaderComponent in a component and I'm having issues getting render to work without errors. The error is below:

```
    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at getFiberTagFromObjectType (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1693:9)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1653:20)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4670:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4727:35)
      at reconcileChildrenAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5098:28)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5089:3)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5524:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5903:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7949:12)
```

More detail:

```
  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6309
    The above error occurred in one of your React components:
        in Unknown (at VirtualizedList.js:761)
        in View (created by View)
        in View (at VirtualizedList.js:767)
        in VirtualizedCellWrapper (at VirtualizedList.js:764)
        in View (created by View)
        in View (at ScrollViewMock.js:31)
        in RCTScrollView (created by _class)
        in _class (at ScrollViewMock.js:29)
        in ScrollView (at VirtualizedList.js:1062)
        in VirtualizedList (at FlatList.js:663)
```

Associated code:

https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L753

Versions:

```
"react": "16.6.3",
"react-native": "0.57.8",
```

Repro:

https://github.com/wmcbain/RNTestingTestingRepro

Is there a suggested way to mock this in order to get past the error?

**Comment by sibelius** [comment]
in which version?

**Comment by wmcbain** [comment]
```
"react": "16.6.3",
"react-native": "0.57.8",
```

Also added to issue

**Comment by thymikee** [comment]
Can you post a repro we can download and inspect? Or send a PR with a failing test

**Comment by wmcbain** [comment]
@thymikee here you go https://github.com/wmcbain/RNTestingTestingRepro

**Comment by thymikee** [comment]
I won't have time to triage this in next couple of days. Would use some help :)

**Comment by Esemesek** [comment]
So I investigated this issue and I was able to fix it by removing unnecessary babel plugin.
```diff
diff --git a/babel.config.js b/babel.config.js
index bc6fe94..144910d 100644
--- a/babel.config.js
+++ b/babel.config.js
@@ -2,7 +2,6 @@ module.exports = api => {
   api.cache(true);

   return {
-    presets: ["module:metro-react-native-babel-preset"],
-    plugins: ["@babel/plugin-proposal-class-properties"]
+    presets: ["module:metro-react-native-babel-preset"]
   };
 };
```

This is not an issue with RNTL, just your repository setup.
