### ISSUE TITLE
Bumping version from 11.5.0 to 11.5.1 breaks many tests

### ISSUE THREAD

**Issue by gkartalis** [callstack/react-native-testing-library#1305]
## Ask your Question

Hello friends! 

I updated today (on [this pr](https://github.com/artsy/eigen/pull/8153)) on our project the `@testing-library/react-native` to the latest version 11.5.1 from 11.5.0. 

I expected no breaking changes since it would be a minor upgrade but 28 tests in our suite are failing with the following trace:

```
Error: Trying to detect host component names triggered the following error:

Can't access .root on unmounted test renderer

There seems to be an issue with your configuration that prevents React Native Testing Library from working correctly.
Please check if you are using compatible versions of React Native and React Native Testing Library.

    at getHostComponentNames (/home/circleci/project/node_modules/@testing-library/react-native/src/helpers/host-component-names.tsx:47:11)
    at isTextInput (/home/circleci/project/node_modules/@testing-library/react-native/src/fireEvent.ts:22:31)
    at isTextInput (/home/circleci/project/node_modules/@testing-library/react-native/src/fireEvent.ts:58:7)
    at isEventEnabled (/home/circleci/project/node_modules/@testing-library/react-native/src/fireEvent.ts:80:18)
    at findEventHandler (/home/circleci/project/node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
    at findEventHandler (/home/circleci/project/node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
    at findEventHandler (/home/circleci/project/node_modules/@testing-library/react-native/src/fireEvent.ts:112:19)
    at Function.pressHandler [as press] (/home/circleci/project/node_modules/@testing-library/react-native/src/fireEvent.ts:131:14)
    at press (/home/circleci/project/src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx:233:29)
    at fn (/home/circleci/project/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13452:12)
    at batchedUpdates (/home/circleci/project/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15280:14)
    at _callee3$ (/home/circleci/project/src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx:233:9)
    at call (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.tryCatch [as _invoke] (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator._invoke [as next] (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
    at call (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
    at tryCatch (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:154:20)
    at invoke (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:164:13)
    at handler (/home/circleci/project/node_modules/core-js/modules/es.promise.js:116:18)
    at callReaction (/home/circleci/project/node_modules/core-js/modules/es.promise.js:141:7)
    at invokeTheCallbackFunction (/home/circleci/project/node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)
    at /home/circleci/project/node_modules/jsdom/lib/jsdom/browser/Window.js:554:9
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
```

Should I have done any config step before just updating the dependency? 

(by the way we are using react-native version 0.66.5 as you can see [here](https://github.com/artsy/eigen/blob/main/package.json#L160))

**Comment by mdjastrzebski** [comment]
@gkartalis thanks for letting us know, we are aware of this error.

Other users (#1302) reported receiving this error for cases when using explicit `act` wrapper over RNTL functions like `fireEvent`. 

```ts
// This raises error
act(() => {
  fireEvent(view);
});

// This does not raise event
fireEvent(view);
```

Explicitly wrapping RNTL utils like `fireEvent` is not needed, as RNTL by itself calls `act` in the necessary places.

Are all/some of your failing tests using explicit `act`? If so, you can probably remove all of these explicit `act` calls.

We plan to release 11.5.1 which fixes this error soon, this might be however, good prompt to get rid of unnecessary `act` calls.

**Comment by gkartalis** [comment]
Wow, that is a great way of getting rid of all fireEvent wrapped with act 😅, tried it out on some of the failing tests and that was the reason! 

Then I am closing this. Thanks a lot @mdjastrzebski

**Comment by gkartalis** [comment]
Checked again, all the tests were failing due to wrapping `fireEvent` with `act` removed that and it is working! Thanks again
