### ISSUE TITLE
Cannot read properties of null (reading 'createEvent')

### ISSUE THREAD

**Issue by dingsq820** [callstack/react-native-testing-library#1446]
`render(
    // eslint-disable-next-line react/jsx-filename-extension
    <NavigationContainer>
      <Provider store={store}>{ui}</Provider>
    </NavigationContainer>
  );`
The provided testing code package that uses @testing-library/react-native produces the following error.

`node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11351
      var evt = document.createEvent('Event');
                         ^

TypeError: Caught error after test environment was torn down

Cannot read properties of null (reading 'createEvent')
    at Object.invokeGuardedCallbackDev (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11351:26)
    at invokeGuardedCallback (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
    at commitRootImpl (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14112:9)
    at unstable_runWithPriority (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
    at commitRoot (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14011:3)
    at performSyncWorkOnRoot (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13440:3)
    at /Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
    at unstable_runWithPriority (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
    at flushSyncCallbackQueueImpl (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2532:9)
    at flushSyncCallbackQueue (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2519:3)
    at batchedUpdates (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13459:7)
    at act (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15280:14)
    at fn (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/@testing-library/react-native/src/render.tsx:106:8)
    at forEach (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/@testing-library/react-native/src/cleanup.ts:9:32)
    at Set.forEach (<anonymous>)
    at cleanup (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/@testing-library/react-native/src/cleanup.ts:9:16)
    at Object.<anonymous> (/Users/linkage/Desktop/dingsq/开发/codecommit/dw-app/node_modules/@testing-library/react-native/src/index.ts:15:14)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:449:9)`

**Comment by mdjastrzebski** [comment]
@dingsq820 your question is not clear? From the error message I would assume that it has something to do with your React component code running after test has been tore down, i.e. you would have to add a proper `findBy*` query or `waitFor` statement to keep your test running until your async component changes actually finish.

Other than this general advise this issue is not actionable from our side. In order to do something more we would need a **minimal** reproduction scenario how to reproduce it locally. Please use our [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) as a base that.

**Comment by dingsq820** [comment]
After rendering, the code 【await screen.findAllByText('test');】 is executed.

**Comment by mdjastrzebski** [comment]
@dingsq820 this is still not reproducible from our perspective. In order to do something more we would need a minimal reproduction scenario how to reproduce it locally. Please use our [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) as a base that. If not provided, I will have to close this issue as not reproducible.

**Comment by mdjastrzebski** [comment]
Closing as stale.
