### ISSUE TITLE
Trying to detect host component names triggered the following error

### ISSUE THREAD

**Issue by SolankiYogesh** [callstack/react-native-testing-library#1472]
## Describe the bug

Trying to detect host component names triggered the following error in react-native-modal

## Expected behavior

package should work with  react-native-modal

## Steps to Reproduce

import  react native modal  and use anywhere in component

```import React from 'react'
import {Dimensions, ImageSourcePropType, StyleSheet} from 'react-native'
import ReactNativeModal from 'react-native-modal'
import styled from 'styled-components/native'

import {Colors, Images} from '../Theme'
import {GettingText} from '../Theme/CommonStyles'
import {Fonts} from '../Theme/Fonts'
import {moderateScale, scale, verticalScale} from '../Theme/Responsive'
import AppButton from './AppButton'
import BackButton from './BackButton'

interface AppAlertModalProps {
  onClose?: () => void
  topText?: string
  middleText?: string
  onPress?: () => void
  btnText?: string
  image?: ImageSourcePropType
  isVisible?: boolean
}
const AppAlertModal = (props: AppAlertModalProps) => {
  const {
    onClose = () => {},
    onPress = () => {},
    topText = '',
    middleText = '',
    btnText = '',
    image = null,
    isVisible = false
  } = props
  const {height} = Dimensions.get('screen')

  return (
    <ReactNativeModal deviceHeight={height} statusBarTranslucent isVisible={isVisible}>
      <Container>
        <BackButton
          onPress={onClose}
          imageStyle={styles.imageStyle}
          parentStyle={styles.closeImage}
          image={Images.close}
          isHeader
          colors={[Colors.greyShadeFAF7, Colors.greyShadeEFF]}
          style={styles.btnStyle}
        />
        {image && <ImageContainer source={image} resizeMode={'contain'} />}
        <InnerContainer>
          <GettingText isCenter>{topText}</GettingText>
          <CreateAnAccountText isCenter>{middleText}</CreateAnAccountText>
        </InnerContainer>
        <AppButton
          title={btnText}
          onPress={() => {
            onClose()
            onPress()
          }}
          textStyle={styles.textStyle}
        />
      </Container>
    </ReactNativeModal>
  )
}

export default AppAlertModal
const Container = styled.View`
  background-color: ${Colors.white};
  border-radius: 28px;
  padding: 10px;
  align-items: center;
  padding-bottom: ${verticalScale(29)}px;
  padding-top: ${verticalScale(40)}px;
`

const ImageContainer = styled.Image`
  margin-top: 10px;
  margin-bottom: 10px;
`

const InnerContainer = styled.View`
  width: 90%;
`
export const CreateAnAccountText = styled.Text`
  font-family: ${Fonts.ThemeMedium};
  font-size: ${moderateScale(14)}px;
  color: ${Colors.greyShade9797};
  text-align: ${(props: any) => (props.isCenter ? 'center' : 'left')};
  margin-bottom: 10px;
`
const styles = StyleSheet.create({
  closeImage: {
    position: 'absolute',
    right: scale(10),
    top: verticalScale(10),
    borderRadius: moderateScale(15)
  },
  imageStyle: {
    width: '35%',
    height: '35%',
    tintColor: Colors.greyShade595
  },
  textStyle: {
    fontSize: moderateScale(16),
    fontFamily: Fonts.ThemeMedium
  },
  btnStyle: {
    height: verticalScale(40),
    width: verticalScale(40),
    borderRadius: moderateScale(10)
  }
})
```

## Screenshots

![image](https://github.com/callstack/react-native-testing-library/assets/70507671/8f1839aa-c266-42c4-89a0-01651b2b3f43)

## Versions

    "@testing-library/jest-native": "^5.4.3",
    "@testing-library/react-native": "^12.2.2",

**Comment by mdjastrzebski** [comment]
@SolankiYogesh You screenshot has error information actually cropped out. Pls provide full error info. It would greatly increase the chances of solving this issue should you provide a **minimal reproduction case**, hopefully based on our [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic)

**Comment by SolankiYogesh** [comment]
FAIL  __tests__/LoginScreen.test.tsx
  ● Console

    console.error
      Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
      
      Check the render method of `AppAlertModal`.
          at AppAlertModal (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/src/Components/AppAlertModal.tsx:24:5)
          at View
          at Component (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/react-native/jest/mockComponent.js:28:18)
          at StyledNativeComponent (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/styled-components/native/dist/styled-components.native.cjs.js:5949:29)
          at Styled(View)
          at View
          at Component (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/react-native/jest/mockComponent.js:28:18)
          at StyledNativeComponent (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/styled-components/native/dist/styled-components.native.cjs.js:5949:29)
          at Styled(View)
          at AppContainer (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/src/Components/AppContainer.tsx:21:5)
          at LoginScreen (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/src/Container/LoginFlow/LoginScreen/LoginScreen.tsx:33:29)

      33 |
      34 |   return (
    > 35 |     <ReactNativeModal deviceHeight={height} statusBarTranslucent isVisible={isVisible}>
         |     ^
      36 |       <Container>
      37 |         <BackButton
      38 |           onPress={onClose}

      at printWarning (node_modules/react/cjs/react-jsx-runtime.development.js:97:30)
      at error (node_modules/react/cjs/react-jsx-runtime.development.js:71:7)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-runtime.development.js:1242:7)
      at jsxWithValidationDynamic (node_modules/react/cjs/react-jsx-runtime.development.js:1299:12)
      at AppAlertModal (src/Components/AppAlertModal.tsx:35:5)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6256:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10702:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12151:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15801:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15735:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15707:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15412:20)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2594:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2665:24)
      at Object.act (node_modules/react/cjs/react.development.js:2519:11)
      at renderWithAct (node_modules/@testing-library/react-native/src/render-act.ts:13:16)
      at renderInternal (node_modules/@testing-library/react-native/src/render.tsx:62:33)
      at render (node_modules/@testing-library/react-native/src/render.tsx:32:10)
      at Object.<anonymous> (__tests__/LoginScreen.test.tsx:12:31)

    console.error
      The above error occurred in the <AppAlertModal> component:
      
          at AppAlertModal (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/src/Components/AppAlertModal.tsx:24:5)
          at View
          at Component (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/react-native/jest/mockComponent.js:28:18)
          at StyledNativeComponent (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/styled-components/native/dist/styled-components.native.cjs.js:5949:29)
          at Styled(View)
          at View
          at Component (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/react-native/jest/mockComponent.js:28:18)
          at StyledNativeComponent (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/node_modules/styled-components/native/dist/styled-components.native.cjs.js:5949:29)
          at Styled(View)
          at AppContainer (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/src/Components/AppContainer.tsx:21:5)
          at LoginScreen (/Users/mac-2/Desktop/SolankiYogesh/reeva-frontend/REEVA/src/Container/LoginFlow/LoginScreen/LoginScreen.tsx:33:29)
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      10 | import English from '../src/Resources/Locales/English'
      11 |
    > 12 | describe('LoginScreen', () => {
         |                               ^
      13 |   const mock = new MockAdapter(axios)
      14 |   it('renders correctly', () => {
      15 |     const {getByTestId} = render(<LoginScreen />)

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8581:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8614:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3903:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3924:9)
      at commitLayoutEffectOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13165:13)
      at commitLayoutMountEffects_complete (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14254:9)
      at commitLayoutEffects_begin (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14240:7)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14225:3)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16052:5)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15923:5)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15444:3)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2594:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2665:24)
      at Object.act (node_modules/react/cjs/react.development.js:2519:11)
      at renderWithAct (node_modules/@testing-library/react-native/src/render-act.ts:13:16)
      at renderInternal (node_modules/@testing-library/react-native/src/render.tsx:62:33)
      at render (node_modules/@testing-library/react-native/src/render.tsx:32:10)
      at Object.<anonymous> (__tests__/LoginScreen.test.tsx:12:31)

  ● LoginScreen › renders correctly

    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `AppAlertModal`.

      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17503:17)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17529:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5718:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5776:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9901:28)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10762:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12151:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15801:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15735:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15707:7)

**Comment by SolankiYogesh** [comment]
@mdjastrzebski here is the full error

**Comment by mdjastrzebski** [comment]
@SolankiYogesh I do not see any part mentioning detect host component names functionality. Am I missing something? From the error:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

I would rather assume that you might have duplicate `react` native imports or your `react-test-renderer` does not match your `react` import. Pls post you `package.json`'s `deps` and `devDeps`.

**Comment by SolankiYogesh** [comment]
{
  "name": "REEVA",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest --watchAll --detectOpenHandles",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "ip": "react-native run-ios --simulator='iPhone 11 Pro Max'",
    "postinstall": "react-native setup-ios-permissions && pod-install",
    "clean": "npm start --reset-cache",
    "linter": "eslint --fix 'src/**/*.{js,jsx,ts,tsx}'",
    "prettier": "prettier --write 'src/**/*.{js,jsx,ts,tsx}'",
    "real": "npx react-native run-ios --udid  00008030-000E6D1E2E44802E",
    "cleanup": "react-native-clean-project"
  },
  "reactNativePermissionsIOS": [
    "Microphone",
    "MediaLibrary",
    "PhotoLibrary",
    "Contacts",
    "SpeechRecognition",
    "Camera"
  ],
  "dependencies": {
    "@gorhom/bottom-sheet": "^4.4.5",
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.17.12",
    "@react-native-community/netinfo": "^9.3.10",
    "@react-native-firebase/app": "^17.5.0",
    "@react-native-firebase/crashlytics": "^17.5.0",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-native-voice/voice": "^3.2.4",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.3",
    "@sayem314/react-native-keep-awake": "^1.2.0",
    "@thevsstech/react-native-skeleton": "^2.0.11",
    "axios": "^1.3.4",
    "axios-mock-adapter": "^1.21.5",
    "bad-words": "^3.0.4",
    "fbemitter": "^3.0.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-ios": "^4.2.0",
    "lottie-react-native": "^6.1.2",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-fast-compare": "^3.2.1",
    "react-native": "0.70.6",
    "react-native-animated-pagination-dots": "^0.1.73",
    "react-native-animated-typewriter": "^1.0.6",
    "react-native-asset": "^2.1.0",
    "react-native-auto-size-text": "^1.1.1",
    "react-native-background-timer": "^2.4.1",
    "react-native-clean-project": "^4.0.1",
    "react-native-config": "^1.5.0",
    "react-native-contacts": "^7.0.5",
    "react-native-device-info": "^10.4.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.10.2",
    "react-native-get-random-values": "^1.8.0",
    "react-native-iap": "^12.10.5",
    "react-native-image-crop-picker": "^0.39.0",
    "react-native-in-app-review": "^4.3.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.7.3",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.1.4",
    "react-native-parallax-scroll-view": "github:khanjandobariya/react-native-parallax-scroll-view",
    "react-native-permissions": "^3.7.3",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-share": "^8.2.2",
    "react-native-sound": "^0.11.2",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.8.0",
    "react-native-system-setting": "github:khanjandobariya/react-native-system-setting",
    "react-native-tab-view": "^3.5.1",
    "react-native-webview": "^12.1.0",
    "react-redux": "^8.0.5",
    "react-usestateref": "^1.0.8",
    "redux": "^4.2.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "styled-components": "^5.3.8",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.22.11",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@testing-library/jest-native": "^5.4.3",
    "@testing-library/react-native": "^12.2.2",
    "@tsconfig/react-native": "^2.0.2",
    "@types/bad-words": "^3.0.1",
    "@types/d3-shape": "^3.1.1",
    "@types/fbemitter": "^2.0.32",
    "@types/jest": "^26.0.23",
    "@types/lodash": "^4.14.191",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.71.5",
    "@types/react-native-background-timer": "^2.0.0",
    "@types/react-native-typing-animation": "^0.1.0",
    "@types/react-test-renderer": "^18.0.0",
    "@types/redux-logger": "^3.0.9",
    "@types/styled-components": "^5.1.26",
    "@types/uuid": "^9.0.1",
    "@typescript-eslint/eslint-plugin": "^5.54.1",
    "@typescript-eslint/parser": "^5.54.1",
    "babel-jest": "^26.6.3",
    "eslint": "^8.36.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-config-standard-with-typescript": "^34.0.0",
    "eslint-import-resolver-typescript": "^3.5.3",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-n": "^15.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.0.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "husky": "^8.0.2",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "pod-install": "0.1.38",
    "prettier": "^2.8.3",
    "react-test-renderer": "18.1.0",
    "typescript": "^5.2.2"
  },
  "jest": {
    "preset": "react-native",
    "setupFilesAfterEnv": [
      "<rootDir>/jest.setup.js"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(@react-native|react-native-auto-size-text|react-native-reanimated|react-native-modal|react-native-keyboard-aware-scroll-view|react-native|@react-native-community/netinfo|axios|@invertase/react-native-apple-authentication)/)"
    ]
  }
}

**Comment by SolankiYogesh** [comment]
@mdjastrzebski .

**Comment by SolankiYogesh** [comment]
"dependencies": {
    "@gorhom/bottom-sheet": "^4.4.5",
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.17.12",
    "@react-native-community/netinfo": "^9.3.10",
    "@react-native-firebase/app": "^17.5.0",
    "@react-native-firebase/crashlytics": "^17.5.0",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-native-voice/voice": "^3.2.4",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.3",
    "@sayem314/react-native-keep-awake": "^1.2.0",
    "@thevsstech/react-native-skeleton": "^2.0.11",
    "axios": "^1.3.4",
    "axios-mock-adapter": "^1.21.5",
    "bad-words": "^3.0.4",
    "fbemitter": "^3.0.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-ios": "^4.2.0",
    "lottie-react-native": "^6.1.2",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-fast-compare": "^3.2.1",
    "react-native": "0.70.6",
    "react-native-animated-pagination-dots": "^0.1.73",
    "react-native-animated-typewriter": "^1.0.6",
    "react-native-asset": "^2.1.0",
    "react-native-auto-size-text": "^1.1.1",
    "react-native-background-timer": "^2.4.1",
    "react-native-clean-project": "^4.0.1",
    "react-native-config": "^1.5.0",
    "react-native-contacts": "^7.0.5",
    "react-native-device-info": "^10.4.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.10.2",
    "react-native-get-random-values": "^1.8.0",
    "react-native-iap": "^12.10.5",
    "react-native-image-crop-picker": "^0.39.0",
    "react-native-in-app-review": "^4.3.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.7.3",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.1.4",
    "react-native-parallax-scroll-view": "github:khanjandobariya/react-native-parallax-scroll-view",
    "react-native-permissions": "^3.7.3",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-share": "^8.2.2",
    "react-native-sound": "^0.11.2",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.8.0",
    "react-native-system-setting": "github:khanjandobariya/react-native-system-setting",
    "react-native-tab-view": "^3.5.1",
    "react-native-webview": "^12.1.0",
    "react-redux": "^8.0.5",
    "react-usestateref": "^1.0.8",
    "redux": "^4.2.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "styled-components": "^5.3.8",
    "uuid": "^9.0.0"
  },  


"devDependencies": {
    "@babel/core": "^7.22.11",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@testing-library/jest-native": "^5.4.3",
    "@testing-library/react-native": "^12.2.2",
    "@tsconfig/react-native": "^2.0.2",
    "@types/bad-words": "^3.0.1",
    "@types/d3-shape": "^3.1.1",
    "@types/fbemitter": "^2.0.32",
    "@types/jest": "^26.0.23",
    "@types/lodash": "^4.14.191",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.71.5",
    "@types/react-native-background-timer": "^2.0.0",
    "@types/react-native-typing-animation": "^0.1.0",
    "@types/react-test-renderer": "^18.0.0",
    "@types/redux-logger": "^3.0.9",
    "@types/styled-components": "^5.1.26",
    "@types/uuid": "^9.0.1",
    "@typescript-eslint/eslint-plugin": "^5.54.1",
    "@typescript-eslint/parser": "^5.54.1",
    "babel-jest": "^26.6.3",
    "eslint": "^8.36.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-config-standard-with-typescript": "^34.0.0",
    "eslint-import-resolver-typescript": "^3.5.3",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-n": "^15.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.0.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "husky": "^8.0.2",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "pod-install": "0.1.38",
    "prettier": "^2.8.3",
    "react-test-renderer": "18.1.0",
    "typescript": "^5.2.2"
  },
  
@mdjastrzebski

**Comment by SolankiYogesh** [comment]
can you please add react-native-modal test cases in your example app @mdjastrzebski

**Comment by pierrezimmermannbam** [comment]
@SolankiYogesh I can't reproduce your issue with the infos you provide. The following test works in example/basic in the RNTL repo, provided that the `transformIgnorePatterns` option of jest is correctly configured.

```tsx
import { render } from '@testing-library/react-native';
import { Text } from 'react-native';
import Modal from 'react-native-modal';

const TestComponent = () => {
  return (
    <Modal>
      <Text>hello</Text>
    </Modal>
  );
};

test('renders modal fine', () => {
  render(<TestComponent />);
});
```

You can try to run this test in your project first to narrow the error to the Modal from `react-native-modal`. Then if it still fails it means that there is something wrong with your test config, probably a mock somewhere either of `react-native-modal` or `react-native`. 

If you can't find the issue then provide a reproducible demo, otherwise we won't be able to assist you further

**Comment by mdjastrzebski** [comment]
@SolankiYogesh also make sure you do not mock `react-native` like [this](https://github.com/callstack/react-native-testing-library/issues/1365#issuecomment-1724273140).

**Comment by mdjastrzebski** [comment]
@SolankiYogesh take a look at this [Troubleshooting Guide entry](https://callstack.github.io/react-native-testing-library/docs/troubleshooting#undefined-component-error) which is discussing one common issue for the error you are facing:
> "Trying to detect host component names triggered the following error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.":

**Comment by SolankiYogesh** [comment]
i don't know whats happening here but its working finr after adding below line into jest setup config

ReactNativeModal.getDerivedStateFromProps = (nextProps) => nextProps ?? null


![image](https://github.com/callstack/react-native-testing-library/assets/70507671/75ce797d-e44a-4c53-bb53-fc4921d08f8c)
