### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string

### ISSUE THREAD

**Issue by DanyGZ** [callstack/react-native-testing-library#274]
## Versions
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-testing-library": "^1.13.0",
"react-test-renderer": "^16.9.0"

## Description
I am creating test files for "Scenes". I am creating one test file per scene. In some scenes, I'm using custom components. When I try to render a scene, I'm getting an error related to my custom component:
 ```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `CustomRow`.

at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14806:34
      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14809:13)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14830:15)
      at createChild (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4634:28)
      at reconcileChildrenArray (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4885:25)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5222:14)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7345:28)
      at updateHostComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7824:3)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9164:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12981:12)

  console.error node_modules/react/cjs/react.development.js:172
```

## Reproducible Demo
This is the code of my scene:
```
import React from 'react';
import { View, Text, SafeAreaView, TextInput } from 'react-native';
import CustomRow from '_molecules/custom_row';

class DetailScene extends React.Component {
       render() {
              return (
              <SafeAreaView style={{ flex: 1, backgroundColor: Colors.WHITE }}>
                <CustomRow
                    name={this.props.route.params.name}
                    ip_address={this.props.route.params.ipAddress}
                    activeOpacity={1}
                    rowColor={Colors.COMPONENTS_BACKGROUND} />
             </SafeAreaView>
            );
      };
}
export default DetailScene;
```

This is the code of my "CustomRow" component:

```
import React from 'react';
import { View, Text, TouchableHighlight } from 'react-native';

class CustomRow extends React.Component {
        state = {
             height: 0,
        }

        render() {
              return(
                      <TouchableHighlight
                         disabled={this.props.disabled}
                         activeOpacity={this.props.activeOpacity}
                        underlayColor={Colors.SEPARATOR_LINE}
                        onPress={() => { this._clickElement() }}>
                      </TouchableHighlight>
              );
        };
}
export default CustomRow;
```

And this is how I'm trying to test the scene:

```
/**
 * @format
 */

import 'react-native';
import React from 'react';

import DetailScene from '_scenes/detail/index';
import { render } from 'react-native-testing-library';


test('Should render the landing page without crashing', () => {
    const route = {
        params: { 
            name:'MFP1',
            ipAddress:'1.1.1.1',
            status: ['None']
        } 
    }
    const rendered = render(<DetailScene route={route} />).toJSON();
    expect(rendered).toBeTruthy();
});
```

As a final comment, the app is working correctly, only the test is crashing.

**Comment by thymikee** [comment]
Do you have a repro we could download? Hard to say what's wrong from this code

**Comment by thymikee** [comment]
@DanyGZ ping :)
