### ISSUE TITLE
Test failure related to LogBox

### ISSUE THREAD

**Issue by jtstodola** [callstack/react-native-testing-library#505]
This is possibly a RN issue not a testing library issue. But, I have no issues running the app.

The test passes on RN 0.59 to 0.62 but with the new LogBox work something is going wrong.

I'm guessing we're catching some sort of error and it's trying to throw up a logbox error but the app is torn down already. I'm not certain how to fix that, if it's actually an error and has to do with how I wrote the test, let me know what you all think.

If I set LogBox.ignoreAllLogs(); it still errors in this same way.

Stack trace for one of the tests that is failing.

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at parseErrorStack (node_modules/react-native/Libraries/Core/Devtools/parseErrorStack.js:52:26)
      at Immediate._onImmediate (node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:191:48)
node_modules/react-native/Libraries/Core/Devtools/parseErrorStack.js:54
  var stack = Array.isArray(e.stack) ? e.stack : global.HermesInternal ? convertHermesStack(parseHermesStack(e.stack)) : stacktraceParser.parse(e.stack).map(function (frame) {
                                                                                                                                          ^

TypeError: stacktraceParser.parse is not a function
    at parseErrorStack (node_modules/react-native/Libraries/Core/Devtools/parseErrorStack.js:60:24)
    at reportException (node_modules/react-native/Libraries/Core/ExceptionsManager.js:63:19)
    at Object.handleException (node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:5)
    at reportLogBoxError (node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:108:21)
    at Immediate.<anonymous> (node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:217:7)
    at processImmediate (internal/timers.js:456:21)
```

## Versions
```
  npmPackages:
    @testing-library/react-native: ^7.0.1 => 7.0.1
    react: 16.11.0 => 16.11.0
    react-native: ^0.63.2 => 0.63.2
    react-test-renderer: 16.11.0 => 16.11.0
```

**Comment by thymikee** [comment]
I appreciate the report, but this is not an issue with this library. Can you report it in `react-native` repository? Thanks!
