### ISSUE TITLE
Can't test a component that uses a FlatList

### ISSUE THREAD

**Issue by search654321** [callstack/react-native-testing-library#849]
I have a component that uses a FlatList like this
```js
const DropdownContent = ({ data, field, type, onSelect }) => {
	return (
		<View style={baseStyles.container}>
			<View style={baseStyles.row}>
				<FlatList
					data={data}
					keyExtractor={({ id }, index) => `DropdownContent-${id || index}`}
					renderItem={({ item }) => (
						<View style={baseStyles.card}>
							<TouchableWithoutFeedback onPress={() => onSelect(field, item)}>
								<Text style={baseStyles.sectionContentText}>{item.text}</Text>
							</TouchableWithoutFeedback>
						</View>
					)}
				/>
			</View>
		</View>
	);
};
```

But when I try to render it like this:
```js
it('Reacts to press', () => {
	const data = [
		{
			id: 'id',
			text: 'data',
		},
	];
	const mockPressedFn = jest.fn();

	const { getByText } = render(
		<DropdownContent data={data} field="test-field" onSelect={mockPressedFn} type={SearchInputType.DROPDOWN} />
	);

	fireEvent.press(getByText('data'));

	expect(mockPressedFn).toBeCalledWith('test-field', { text: 'data' });
});
```
I get the following error:

```
The above error occurred in the <NativeViewGestureHandler> component:

        at NativeViewGestureHandler (/Users/project/node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:196:51)
        at /Users/project/node_modules/react-native-gesture-handler/lib/commonjs/handlers/createNativeWrapper.tsx:32:33
        at VirtualizedList (/Users/project/node_modules/react-native/Libraries/Lists/VirtualizedList.js:767:46)
        at FlatList (/Users/project/node_modules/react-native/Libraries/Lists/FlatList.js:394:36)
        at View
        at View (/Users/project/node_modules/react-native/jest/mockComponent.js:19:18)
        at View (/Users/project/components/Themed.tsx:88:10)
        at View
        at View (/Users/project/node_modules/react-native/jest/mockComponent.js:19:18)
        at View (/Users/project/components/Themed.tsx:88:10)
        at DropdownContent (/Users/project/components/shared/DropdownContent.tsx:21:67)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)

 FAIL  components/__tests__/shared/DropdownContent.test.tsx
  <DropdownContent />
    ✕ Reacts to press (163 ms)

  ● <DropdownContent /> › Reacts to press

    Unable to find node on an unmounted component.

      at findHostInstanceWithWarning (node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20401:17)
      at findNodeHandle (node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:21013:20)
      at findNodeHandle (node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:25:10)
      at Handler.componentDidMount (node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:232:33)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11782:24)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14172:9)
      at unstable_runWithPriority (node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:468:12)
```

Is not possible to test FlatList using react-native-testing-library?

**Comment by thymikee** [comment]
Can you post a minimal reproduction? FlatList is supported, so there's likely something else going on

**Comment by AugustinLF** [comment]
There is something wrong with your setup, or an issue outside of the code you're showing. I made a repro with the following code and the test passed.
```tsx
import * as React from "react";
import { render, fireEvent } from "@testing-library/react-native";
import { View, FlatList, TouchableWithoutFeedback, Text } from "react-native";

const DropdownContent = ({ data, field, onSelect }) => {
  return (
    <View>
      <View>
        <FlatList
          data={data}
          keyExtractor={({ id }, index) => `DropdownContent-${id || index}`}
          renderItem={({ item }) => (
            <View>
              <TouchableWithoutFeedback onPress={() => onSelect(field, item)}>
                <Text>{item.text}</Text>
              </TouchableWithoutFeedback>
            </View>
          )}
        />
      </View>
    </View>
  );
};

it("Reacts to press", () => {
  const data = [
    {
      id: "id",
      text: "data",
    },
  ];
  const mockPressedFn = jest.fn();

  const { getByText } = render(
    <DropdownContent data={data} field="test-field" onSelect={mockPressedFn} />
  );

  fireEvent.press(getByText("data"));

  expect(mockPressedFn).toBeCalledWith("test-field", {
    text: "data",
    id: "id",
  });
});
```

I'll close the issue meanwhile, I'll reopen when we'll get more details.
